### ISSUE TITLE
Make the monsters move

### ISSUE THREAD

**Issue by jamilka** [UCSB-CS56-Projects/cs56-games-simple-rpg#13]
Implement the enemies to move around the map and attack the main character. 
Estimated ~200 pts

**Comment by PazZaitGivon** [comment]
looks good

**Comment by vivekpatel42** [comment]
F16 OK (200 pts)

**Comment by SElegans** [comment]
F17 OK (200 pts)

**Comment by SElegans** [comment]
F17 CLOSED
