### ISSUE TITLE
Add a GUI

### ISSUE THREAD

**Issue by bronhuston** [UCSB-CS56-Projects/cs56-games-simple-rpg#2]
Depends #1 
Implement a GUI version of the command line game.

Currently, there is only a Command line version of the game and a non functional gui.

Turn the command line version of the game into a functional GUI version.

estimated ~400

**Comment by vivekpatel42** [comment]
Added working GUI.
Level 1 is now a coherently drawn map. MainCharacter now has a stick figure representation that moves (within bounding box and grass area) according to arrow key input by user. Status bar is drawn according to MainCharacter's HP, MP, and EXP. "Go to shop" button added, which, upon click, opens up a new window that represents the shop and the items available with a "Buy" button.

**Comment by PazZaitGivon** [comment]
Still does not include enemies or gold but fairly solid upgrading from here should still be worth around 200 points

**Comment by vivekpatel42** [comment]
Student branch wasn't merged into master, GUI work not integrated.

**Comment by vivekpatel42** [comment]
F16 OK (400 pts)

**Comment by SElegans** [comment]
Moving continued work to seperate issue since GUI is created
F17 CLOSED
