### ISSUE TITLE
Fix game logic to allow for continued gameplay after accessing the Shop/Inventory Display

### ISSUE THREAD

**Issue by extrabutter** [UCSB-CS56-Projects/cs56-games-simple-rpg#21]
Currently, after clicking the "Shop" or "Set Weapon" menus, the MainCharacter no longer responds to arrow key controls and the 'esc' key cannot be used to quit the game, making the game essentially unplayable.

Estimated: 400 Points

**Comment by SElegans** [comment]
F17 OK (400 pts)

**Comment by SElegans** [comment]
F17 CLOSED
