### ISSUE TITLE
Add more Enemies that move onscreen

### ISSUE THREAD

**Issue by dwchojnacki** [UCSB-CS56-Projects/cs56-games-simple-rpg#22]
Currently, there is only one enemy that moves onscreen. And that enemy is programmed to move whenever the Display is redrawn.
I would suggest using the Level's Enemy instance variables to have multiple Enemies onscreen.
Estimated: 200 points

**Comment by dwchojnacki** [comment]
Currently, there is only one enemy that moves onscreen. And that enemy is programmed to move whenever the Display is redrawn.
I would suggest using the Level's Enemy instance variables to have multiple Enemies onscreen.

**Comment by SElegans** [comment]
F17 OK (200 pts)

**Comment by SElegans** [comment]
F17 CLOSED
