### ISSUE TITLE
Add additional Enemy behavior

### ISSUE THREAD

**Issue by dwchojnacki** [UCSB-CS56-Projects/cs56-games-simple-rpg#24]
In its current state, the only thing an Enemy can do in the game is move randomly or move toward the player.
I would suggest adding additional Enemy behavior/movements and allowing them to start a battle with the MainCharacter.
Estimated: 200 points

**Comment by SElegans** [comment]
F17 OK (150 pts)

**Comment by SElegans** [comment]
F17 CLOSED
