### ISSUE TITLE
Add comments for better understanding of the code

### ISSUE THREAD

**Issue by barasuishou** [UCSB-CS56-Projects/cs56-games-simple-rpg#4]
The code for this project is concentrated within 13 different java source code files. I had trouble understanding the code because there weren't many comments explaining exactly what some of the methods did. Add comments to provide clarification for ambiguous source files, methods and variables.

estimated ~200 points

**Comment by jamilka** [comment]
Added detailed comments throughout the files

**Comment by PazZaitGivon** [comment]
this should be around 100 points

**Comment by vivekpatel42** [comment]
F16 ok (75 pts)

**Comment by SElegans** [comment]
Not enough work to be done
F17 CLOSED
