### ISSUE TITLE
Two files exactly the same

### ISSUE THREAD

**Issue by vivekpatel42** [UCSB-CS56-Projects/cs56-games-simple-rpg#6]
TextBox.java and CLIOutput.java are exactly the same, with the exception of TextBox containing regular comments and CLIOutput containing Javadoc commments.

Estimated ~50 points

**Comment by vivekpatel42** [comment]
Resolved the issue by deleting TextBox from the source files.

**Comment by PazZaitGivon** [comment]
good catch
