### ISSUE TITLE
Display movable main character and self-updating status bar

### ISSUE THREAD

**Issue by vivekpatel42** [UCSB-CS56-Projects/cs56-games-simple-rpg#7]
Estimated ~100-150 points

**Comment by vivekpatel42** [comment]
Updated the Display source file so GUI now displays a status bar with MainCharacter's info on the bottom of the JPanel.

**Comment by PazZaitGivon** [comment]
included in making a GUI https://github.com/UCSB-CS56-Projects/cs56-games-simple-rpg/issues/2
closing duplicate
