### ISSUE TITLE
No working map - randomly displays green tiles. no main character representation.

### ISSUE THREAD

**Issue by jamilka** [UCSB-CS56-Projects/cs56-games-simple-rpg#8]
Estimated ~50-100 points

**Comment by jamilka** [comment]
Added a working map with a character that is movable with certain restrictions on the map(main character cannot go into the water tiles)

**Comment by PazZaitGivon** [comment]
included in adding a GUI: https://github.com/UCSB-CS56-Projects/cs56-games-simple-rpg/issues/2
closing duplicate
