### ISSUE TITLE
Extend Shop Capabilities

### ISSUE THREAD

**Issue by vivekpatel42** [UCSB-CS56-Projects/cs56-games-simple-rpg#9]
Further implementation of shop, using MainCharacter's gold and removing items accordingly from selection rectangle (JComboBox) when the "Buy" button is clicked. Buying an item should remove the weapon as an option from the shop and  using up the appropriate amount of gold from MainCharacter's gold.

Estimated ~150 points

**Comment by PazZaitGivon** [comment]
looks good

**Comment by vivekpatel42** [comment]
F16 OK (100 pts)

**Comment by SElegans** [comment]
Issue Fixed
F17 CLOSED
